### PR TITLE
Add editorconfig icon

### PR DESCRIPTION
**Pull request by AlejandroPerezMartin**
Hello @equinusocio, congrats for such a great icon set!

This PR adds the editorconfig icon.

I could not test this on VSCode yet cause I don't really know how to pack it, could you please provide instructions for that?

Thanks!

### CODE REVIEW

**Comment by AlejandroPerezMartin** [comment]
ping @equinusocio 😄

**Comment by equinusocio** [comment]
Hello, sorry for the late response. Thank you for the PR, but the moment [we already set the icon](https://github.com/moxer-theme/moxer-icons-code/blob/dedf786ad458e356c238cc5f028953451a0dfc81/src/declarations/fileExtensions.ts#L122) for the `.editorconfig` file (the small cogs):

Screenshot 2021-04-23 at 08 25 09

Are you suggesting to use a different icon?

**Comment by equinusocio** [comment]
I've updated the editorconfig icon with your in this commit https://github.com/moxer-theme/moxer-icons-code/commit/a0b94f554eb1783169f6ba0dc7a45d11db94a39d

**Comment by AlejandroPerezMartin** [comment]
no worries, yeah, I was suggesting something like this:

Screenshot 2021-04-23 at 09 35 10

thanks!

**Comment by equinusocio** [comment]
Released

**Pull request closed without merging**
